services:
  quotes:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      MYSQL_DSN: root:password@tcp(mysql:3306)/quotesdb
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: quotesdb
    volumes:
      - ./quotes.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 5s
      timeout: 3s
      retries: 2
      start_period: 0s
